# Changes here will be overwritten by Copier
AnswerStrategy: recommended
Authors: Tangi Migot <tangi.migot@gmail.com>
CodeOfConductContact: tangi.migot@gmail.com
JuliaIndentation: 2
JuliaMinVersion: '1.10'
License: MIT
LicenseCopyrightHolders: Tangi Migot
PackageName: JSOBestieTemplate
PackageOwner: JuliaSmoothOptimizers
PackageUUID: 68831218-7a4b-5845-b8cc-89c14679f12c
_commit: v0.13.0
_src_path: https://github.com/abelsiqueira/BestieTemplate.jl
